routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('login', 'LoginController',['only' => ['index', 'store','show','create']])->middleware('CheckUser');

Route::resource('logout', 'LogoutController',['only' => ['index', 'store']]);

// User
Route::group(['namespace'=>'FrontEnd'],function(){

	Route::resource('/', 'HomeController')->names([ 'index' => 'home',  'create' => 'home.create'  ]);
    Route::post('add-cart', 'HomeController@store')->name('home.store');
	Route::resource('category-product', 'CategoryController');
	Route::resource('product-detail', 'DetailController');
	Route::resource('cart', 'CartController');
	Route::resource('cart-address', 'AddressCartController');
	Route::resource('cart-address-vnpay', 'VnpayController');
	Route::resource('wishlist', 'WishlistController');
	Route::resource('history', 'HistoryController');
});

Route::group(['namespace'=>'BackEnd'],function(){


	Route::middleware('CheckLogin')->group(function(){

		Route::resource('dashboard', 'HomeController');
		Route::group(['prefix'=>'dashboard'],function(){
			Route::post('table', 'HomeController@store_table')->name('store.table');
			Route::post('total', 'HomeController@store_total')->name('store.total');
		});
		Route::resource('account', 'AccountController');
		Route::resource('remove', 'RemoveController');

		Route::resource('product', 'ProductController');
		Route::resource('product-gallery','GalleryController');
		Route::resource('slider','SliderController');
		Route::resource('category','CategoryController');
		Route::resource('coupon','CouponController');
		Route::resource('order','OrderController');
		Route::resource('contacts','ContactController');

		Route::resource('sorting', 'SortingController')->only('store');
		Route::resource('list', 'SubCategoryController');

		// Status All
		Route::resource('status','StatusController')->only('store');
	});

});

app/Http/Controllers/FrontEnd/AddressCartController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use Cart;
use App\City;
use App\Order;
use App\Wards;
use App\Coupon;
use App\Customer;
use App\District;
use App\OrderDetail;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class AddressCartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::check() && Cart::content()->count() > 0){
            $city = City::all();
            return view('FrontEnd.addressCart', compact('city'));
        }else{
            return redirect()->route('home');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data = $request->all();

        if($data['action']){
            $output = '';
            if($data['action']=="city"){
                $select_province = District::where('matp',$data['ma_id'])->orderby('maqh','ASC')->get();
                    $output.='<option value="">-- Choose --</option>';
                foreach($select_province as $province){
                    $output.='<option value="'.$province->maqh.'">'.$province->name_district.'</option>';
                }

            }else{

                $select_wards = Wards::where('maqh',$data['ma_id'])->orderby('xaid','ASC')->get();
                $output.='<option value="">-- Choose --</option>';
                foreach($select_wards as $ward){
                    $output.='<option value="'.$ward->xaid.'">'.$ward->name_wards.'</option>';
                }
            }
            echo $output;
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $total = 0;
        $checkout_code = mt_rand();
        if($request->checkout_payment == 'ATM'){
            if($request->checkout_type_payment == 'Vnpay'){

                $vnp_OrderInfo = "TT Fashion Shop";
                $vnp_OrderType = "billpayment";
                foreach(Cart::content() as $key => $cart){
                    $total += ($cart->qty)*($cart->price);
                    if (Session::get('coupon')) {
                        foreach(Session::get('coupon') as $key => $coun){
                            if($coun['coupon_condition']==2){
                                $total_pre = $total+($total*0.02)-($total*($coun['coupon_number']/100));
                                $totalPrice = $total_pre;
                            }else{
                                $total_coupon = ($total+($total*0.02))-$copo['coupon_number'];
                                $totalPrice = $total_coupon;
                            }
                        }
                        $vnp_Amount = $totalPrice * 100;
                    }else{
                        $vnp_Amount = $total * 100;
                    }
                }
                $vnp_Locale = config('app.locale');
                $vnp_BankCode = $request->checkout_bank;
                $vnp_IpAddr = $_SERVER['REMOTE_ADDR'];

                $name_order = $request->checkout_name;
                $email_order = Auth::user()->email;
                $address_order = $request->checkout_address.','.Wards::find($request->checkout_wards)->name_wards.','.District::find($request->checkout_district)->name_district.','.City::find($request->checkout_city)->name_city;
                $phone_number_order = $request->checkout_phone;
                $note_order = $request->checkout_note;
                $code_order = $checkout_code;
                $BankCode_order = $vnp_BankCode;


                $count_order[] = array(
                    'name_order' => $name_order,
                    'email_order' => $email_order,
                    'address_order' => $address_order,
                    'phone_number_order' => $phone_number_order,
                    'note_order' => $note_order,
                    'code_order' => $code_order,
                    'BankCode_order' => $BankCode_order,
                );
                Session::put('order_customer',$count_order);

                $inputData = array(
                    "vnp_Version" => "2.1.0",
                    "vnp_TmnCode" => env('VNP_TMN_CODE'),
                    "vnp_Amount" => $vnp_Amount,
                    "vnp_Command" => "pay",
                    "vnp_CreateDate" => date('YmdHis'),
                    "vnp_CurrCode" => "VND",
                    "vnp_IpAddr" => $vnp_IpAddr,
                    "vnp_Locale" => $vnp_Locale,
                    "vnp_OrderInfo" => $vnp_OrderInfo,
                    "vnp_OrderType" => $vnp_OrderType,
                    "vnp_ReturnUrl" => route('cart-address-vnpay.index'),
                    "vnp_TxnRef" => $checkout_code,
                    "vnp_ExpireDate"=>time().rand(0,100),
                );

                if (isset($vnp_BankCode) && $vnp_BankCode != "") {
                    $inputData['vnp_BankCode'] = $vnp_BankCode;
                }
                ksort($inputData);
                $query = "";
                $i = 0;
                $hashdata = "";
                foreach ($inputData as $key => $value) {
                    if ($i == 1) {
                        $hashdata .= '&' . urlencode($key) . "=" . urlencode($value);
                    } else {
                        $hashdata .= urlencode($key) . "=" . urlencode($value);
                        $i = 1;
                    }
                    $query .= urlencode($key) . "=" . urlencode($value) . '&';
                }

                $vnp_Url = env('VNP_URL') . "?" . $query;
                if (env('VNP_HASH_SECRET')) {
                    $vnpSecureHash = hash_hmac('sha512', $hashdata, env('VNP_HASH_SECRET'));
                    $vnp_Url .= 'vnp_SecureHash=' . $vnpSecureHash;
                }

                return redirect()->to($vnp_Url);
            }else{
                $order = new Order;
                $order->user_id  = Auth::id();
                $order->order_status = 1;
                $order->order_review = 0;
                $order->order_code = $checkout_code;
                $order->save();

                $customer = new Customer();
                $customer->customer_name = $request->checkout_name;
                $customer->customer_address = $request->checkout_address.','.Wards::find($request->checkout_wards)->name_wards.','.District::find($request->checkout_district)->name_district.','.City::find($request->checkout_city)->name_city;
                $customer->customer_phone = $request->checkout_phone;
                $customer->customer_note = $request->checkout_note;
                $customer->customer_pay = 'ATM-PAYPAL';
                $customer->customer_code = $checkout_code;
                $customer->save();

                if(Session::get('cart')==true){
                    foreach(Cart::content() as  $cart){
                        $order_details = new OrderDetail;
                        $order_details->order_code = $checkout_code;
                        $order_details->pro_id  = $cart->id;
                        $order_details->order_de_price = $cart->price;
                        $order_details->order_de_qty = $cart->qty;
                        $order_details->order_review = 0;
                        if (Session::get('coupon')) {
                            foreach (Session::get('coupon') as $cou) {
                                $order_details->order_de_coupon =  $cou['coupon_code'];
                            }
                        }else{
                            $order_details->order_de_coupon =  'no';
                        }
                        $order_details->save();
                    }
                }
                if (Session::get('coupon')) {
                    foreach(Session::get('coupon') as $coun){
                        $coupon_qty = Coupon::where('coupon_code',$coun['coupon_code'])->first();
                        $coupon_qty->coupon_used = ','.Auth::id();
                        $coupon_qty->coupon_qty--;
                        $coupon_qty->save();
                    }
                }
                Session::forget('cart');
                Session::forget('coupon');

                return response()->json([
                    'status'=>200,
                    'message'=> 'Order Successfully'
                ]);
            }
        }else{
            $order = new Order;
            $order->user_id  = Auth::id();
            $order->order_status = 1;
            $order->order_review = 0;
            $order->order_code = $checkout_code;
            $order->save();

            $customer = new Customer();
            $customer->customer_name = $request->checkout_name;
            $customer->customer_address = $request->checkout_address.','.Wards::find($request->checkout_wards)->name_wards.','.District::find($request->checkout_district)->name_district.','.City::find($request->checkout_city)->name_city;
            $customer->customer_phone = $request->checkout_phone;
            $customer->customer_note = $request->checkout_note;
            $customer->customer_pay = $request->checkout_payment;
            $customer->customer_code = $checkout_code;
            $customer->save();

            if(Session::get('cart')==true){
                foreach(Cart::content() as  $cart){
                    $order_details = new OrderDetail;
                    $order_details->order_code = $checkout_code;
                    $order_details->pro_id  = $cart->id;
                    $order_details->order_de_price = $cart->price;
                    $order_details->order_de_qty = $cart->qty;

resources/views/FrontEnd/category.blade.php
@extends('Layout_user')
@section('title')
    {{ $header_name }}
@endsection
@section('content')
    <section class="main-container col2-left-layout">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-8 col-xs-12 col-sm-push-4 col-md-push-3">
                    <!-- Breadcrumbs -->
                    <div class="breadcrumbs" style="float: right;">
                        <ul>
                            <li class="home"> <a href="{{ route('home') }}" title="Go to Home Page">Home</a>
                                <span>/</span>
                            </li>
                            @foreach ($categoryProduct as $cate_pro)
                                @if ($cate_pro->cate_product->category_sub != '')
                                    @php
                                        $cateparent = App\Category::where('category_id', $cate_pro->cate_product->category_sub)->first();
                                        $cateparent2 = App\Category::where('category_id', $cateparent->category_sub)->first();
                                    @endphp
                                    @if ($cateparent2)
                                        <li style="text-transform: lowercase;" class="category1599"> <a href=""
                                                title="">{{ $cateparent2->category_name }}</a> <span>/ </span> </li>
                                    @endif
                                    @if ($cateparent)
                                        <li style="text-transform: lowercase;" class="category1600"> <a href=""
                                                title="">{{ $cateparent->category_name }}</a> <span>/</span> </li>
                                    @endif
                                @endif
                            @endforeach

                            <li style="text-transform: lowercase;" class="category1600"> <a href=""
                                    title="">{{ $header_name }}</a> </li>
                        </ul>
                    </div>
                    <!-- Breadcrumbs End -->
                    <div class="page-title">
                        <h2 class="page-heading"> <span class="page-heading-title">{{ $header_name }}</span>
                        </h2>
                    </div>
                    <div class="category-description std">
                        <div class="slider-items-products">
                            <div id="category-desc-slider" class="product-flexslider hidden-buttons">
                                <div class="slider-items slider-width-col1 owl-carousel owl-theme">

                                    <!-- Item -->
                                    <div class="item"> <a href="#"><img alt=""
                                                src="{{ asset('frontend/images/category-img1.jpg') }}"></a>
                                        <div class="cat-img-title cat-bg cat-box">
                                            <div class="small-tag">Fashion 2016</div>
                                            <h2 class="cat-heading">Women Collection</h2>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
                                        </div>
                                    </div>
                                    <!-- End Item -->

                                    <!-- Item -->
                                    <div class="item"> <a href="#"><img alt=""
                                                src="{{ asset('frontend/images/category-img2.jpg') }}"></a>
                                        <div class="cat-img-title cat-bg cat-box">
                                            <div class="small-tag">Street Style</div>
                                            <h2 class="cat-heading">New Season</h2>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
                                        </div>
                                        <!-- End Item -->

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <article class="col-main" id="table_data">
                        @include('FrontEnd.cate_include');
                    </article>
                    <!--	///*///======    End article  ========= //*/// -->
                </div>
                <aside class="col-left sidebar col-md-3 col-sm-4 col-xs-12 col-sm-pull-8 col-md-pull-9">
                    <div class="side-banner"><img src="{{ asset('frontend/images/side-banner.jpg') }}" alt="banner">
                    </div>

                    <div class="block block-compare" id="loadare">

                    </div>

                    <div class="custom-slider-wrap">
                        <div class="custom-slider-inner">
                            <div class="home-custom-slider">
                                <div>
                                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                        <ol class="carousel-indicators">
                                            <li class="active" data-target="#carousel-example-generic"
                                                data-slide-to="0"></li>
                                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                                        </ol>
                                        <div class="carousel-inner">
                                            <div class="item active"> <img
                                                    src="{{ asset('frontend/images/custom-slide1.jpg') }}" alt="slide3">
                                                <div class="carousel-caption"> <span>Mega Deal</span>
                                                    <p>Save up to <strong>70% OFF</strong> Fahion collection</p>
                                                </div>
                                            </div>
                                            <div class="item"> <img
                                                    src="{{ asset('frontend/images/custom-slide2.jpg') }}" alt="slide2">
                                                <div class="carousel-caption"> <span>Huge <strong>sale</strong></span>
                                                    <p>Save up to <strong>70% OFF</strong> Fahion collection</p>
                                                </div>
                                            </div>
                                            <div class="item"> <img
                                                    src="{{ asset('frontend/images/custom-slide3.jpg') }}" alt="slide1">
                                                <div class="carousel-caption"> <span>Hot <strong>Deal</strong></span>
                                                    <p>Save up to <strong>70% OFF</strong> Fahion collection</p>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="left carousel-control" href="#" data-slide="prev"> <span
                                                class="sr-only">Previous</span> </a> <a
                                            class="right carousel-control" href="#" data-slide="next"> <span
                                                class="sr-only">Next</span> </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="block block-list block-viewed">
                        <div class="block-title"> Recently Viewed </div>
                        <div class="block-content">
                            <ol id="recently-viewed-items">
                                <li class="item odd">
                                    <p class="product-name"><a href="#"> Armchair with Box-Edge Upholstered Arm</a></p>
                                </li>
                                <li class="item even">
                                    <p class="product-name"><a href="#"> Pearce Upholstered Slee pere</a></p>
                                </li>
                                <li class="item last odd">
                                    <p class="product-name"><a href="#"> Sofa with Box-Edge Down-Blend Wrapped
                                            Cushions</a></p>
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="block block-poll">
                        <div class="block-title">Community Poll </div>
                        <form id="pollForm" action="#" method="post" onSubmit="return validatePollAnswerIsSelected();">
                            <div class="block-content">
                                <p class="block-subtitle">What is your favorite Magento feature?</p>
                                <ul id="poll-answers">
                                    <li class="odd">
                                        <input type="radio" name="vote" class="radio poll_vote" id="vote_5" value="5">
                                        <span class="label">
                                            <label for="vote_5">Layered Navigation</label>
                                        </span>
                                    </li>
                                    <li class="even">
                                        <input type="radio" name="vote" class="radio poll_vote" id="vote_6" value="6">
                                        <span class="label">
                                            <label for="vote_6">Price Rules</label>
                                        </span>
                                    </li>
                                    <li class="odd">
                                        <input type="radio" name="vote" class="radio poll_vote" id="vote_7" value="7">
                                        <span class="label">
                                            <label for="vote_7">Category Management</label>
                                        </span>
                                    </li>
                                    <li class="last even">
                                        <input type="radio" name="vote" class="radio poll_vote" id="vote_8" value="8">
                                        <span class="label">
                                            <label for="vote_8">Compare Products</label>
                                        </span>
                                    </li>
                                </ul>
                                <div class="actions">
                                    <button type="submit" title="Vote"
                                        class="button button-vote"><span>Vote</span></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="hot-banner"><img alt="banner"
                            src="{{ asset('frontend/images/hot-trends-banner.jpg') }}"></div>
                </aside>
                <input type="hidden" id="hiden_id_slug" value="{{ $header_id }}">
            </div>
        </div>
    </section>
@endsection
@section('js')
    <script>
        $(document).ready(function() {
            loadCompare();
            $(document).on('click', '.pagination a', function(e) {
                e.preventDefault();
                var page = $(this).attr('href').split('page=')[1];
                fetch_data(page);
            });
            // Change Show
            $(document).on('change', '.change_view', function(e) {
                e.preventDefault();
                var show = $(this).val();

                $.ajax({
                    type: 'get',
                    url: '{{ route('category-product.index') }}',
                    data: {show:show, id:$('#hiden_id_slug').val()},
                    success:function(data){
                        $('#table_data').html(data);
                    }
                });
            });
            $('.click_compare').click(function(){
                window.location.href = '{{ route('wishlist.create') }}';
            });
            $(document).on('click', '.click_clear', function(e) {
                e.preventDefault();
                $.ajax({
                    type: 'post',
                    url: "{{ route('product-detail.store') }}",
                    dataType: 'json',
                    success: function(response) {
                        if(response.status==200){
                            loadCompare();
                        }

                    }
                });

            });
        });
        function fetch_data(page) {
            $.ajax({
                url: "{{ url('category-product/create?page=') }}" +page,
                data: {id:$('#hiden_id_slug').val() },
                success: function(data) {
                    $('#table_data').html(data);
                }
            });
        }

    </script>
@endsection

resources/views/FrontEnd/login.blade.php
@extends('Layout_user')
@section('title')
  Login
@endsection
@section('content')
<!-- Main Container -->
<div class="main-container col1-layout">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <article class="col-main">
          <div class="account-login">
            <div class="page-title">
              <h2>Login or Create an Account</h2>
            </div>
            <fieldset class="col2-set">
              <div class="col-1 new-users"><strong>New Customers</strong>
                <div class="content">
                  <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
                  <div class="buttons-set">
                    <button onclick="window.location='{{ route('login.create') }}';" class="button create-account" type="button"><span>Create an Account</span></button>
                  </div>
                </div>
              </div>
              <div class="col-2 registered-users"><strong>Login Customers</strong>
                <form action="{{ route('login.store') }}" method="post">
                	@csrf
                    <div class="content">
                    <p>If you have an account with us, please log in.</p>
                    <ul class="form-list">
                        <li>
                        <label for="email">Email Address <span class="required">*</span></label>
                        <input type="text" title="Email Address" class="input-text required-entry" id="email" value="{{old('email_login')}}" name="email_login">
                        </li>
                        <li>
                        <label for="pass">Password <span class="required">*</span></label>
                        <input type="password" title="Password" id="pass" class="input-text required-entry validate-password" name="password_login">
                        </li>
                    </ul>
                    {{--  <p class="required">* Required Fields</p>  --}}
                    <div class="buttons-set">
                        <button id="send2" name="send" type="submit" class="button login"><span>Login</span></button>
                        <a class="forgot-word" href="#">Forgot Your Password?</a> </div>
                    </div>
                </form>
              </div>
            </fieldset>
          </div>
        </article>
        <!--	///*///======    End article  ========= //*/// -->
      </div>
    </div>
  </div>
</div>
<!-- Main Container End -->
@endsection

resources/views/FrontEnd/paginatoin.blade.php
@if ($paginator->hasPages())
    <!-- Pagination -->
    <label>Page:</label>
    <ul class="pagination">
        {{-- Previous Page Link --}}
        @if ($paginator->onFirstPage())
            <li>
                <a href="#">&laquo;</a>
            </li>
        @else
            <li>
                <a href="{{ $paginator->previousPageUrl() }}">&laquo;</a>
            </li>
        @endif
        {{-- Pagination Elements --}}
        @foreach ($elements as $element)
            {{-- Array Of Links --}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="active"><a>{{ $page }}</a></li>
                    @elseif (($page == $paginator->currentPage() + 1 || $page == $paginator->currentPage() + 2) || $page == $paginator->lastPage())
                        <li><a href="{{ $url }}">{{ $page }}</a></li>
                    @elseif ($page == $paginator->lastPage() - 1)
                        <li class="disabled"><a><i class="fa fa-ellipsis-h"></i></a></li>
                    @endif
                @endforeach
            @endif
        @endforeach
        {{-- Next Page Link --}}
        @if ($paginator->hasMorePages())
            <li>
                <a href="{{ $paginator->nextPageUrl() }}">&raquo;</a>
            </li>
        @else
        <li><a href="#">&raquo;</a></li>
        @endif
    </ul>
    <!-- Pagination -->
@endif