routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('login', 'LoginController',['only' => ['index', 'store','show','create']])->middleware('CheckUser');

Route::resource('logout', 'LogoutController',['only' => ['index', 'store']]);

// User
Route::group(['namespace'=>'FrontEnd'],function(){

	Route::resource('/', 'HomeController')->names([ 'index' => 'home',  'create' => 'home.create'  ]);
    Route::post('add-cart', 'HomeController@store')->name('home.store');
	Route::resource('category-product', 'CategoryController');
	Route::resource('product-detail', 'DetailController');
	Route::resource('cart', 'CartController');
	Route::resource('cart-address', 'AddressCartController');
	Route::resource('cart-address-vnpay', 'VnpayController');
	Route::resource('wishlist', 'WishlistController');
	Route::resource('history', 'HistoryController');
});

Route::group(['namespace'=>'BackEnd'],function(){


	Route::middleware('CheckLogin')->group(function(){

		Route::resource('dashboard', 'HomeController');
		Route::group(['prefix'=>'dashboard'],function(){
			Route::post('table', 'HomeController@store_table')->name('store.table');
			Route::post('total', 'HomeController@store_total')->name('store.total');
		});
		Route::resource('account', 'AccountController');
		Route::resource('remove', 'RemoveController');

		Route::resource('product', 'ProductController');
		Route::resource('product-gallery','GalleryController');
		Route::resource('slider','SliderController');
		Route::resource('category','CategoryController');
		Route::resource('coupon','CouponController');
		Route::resource('order','OrderController');
		Route::resource('contacts','ContactController');

		Route::resource('sorting', 'SortingController')->only('store');
		Route::resource('list', 'SubCategoryController');

		// Status All
		Route::resource('status','StatusController')->only('store');
	});

});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = "gallery";

    protected $primaryKey = 'gallery_id';
    protected $guarded = [];
}

app/Http/Controllers/BackEnd/AccountController.php
<?php

namespace App\Http\Controllers\BackEnd;


use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;


class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (request()->ajax()) {
            return datatables()->of(User::where('id','!=',Auth::user()->id)->orderBy('id','desc')->get())
                ->addColumn('action', function($data){
                    $button = '<button type="button" name="edit" id="edit_account" data-account_id="'.$data->id.'" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i></button>';
                    $button .= '&nbsp;&nbsp;';
                    $button .= '<button type="button" name="delete" id="delete_account" data-account_id="'.$data->id.'" class="btn  btn-outline btn-danger delete"><i class="fa fa-trash"></i></button>';
                    return $button;
                })
                ->addColumn('status', function($data){
                    if ($data->isOnline()) {
                        $status = '<span class="tag-style expiry" style="font-weight: bold;">Online</span>';
                    }else{
                        $status = '<span class="tag-style expired" style="font-weight: bold;">Offline</span>';
                    }
                    return $status;
                })
                ->rawColumns(['action','status'])
                ->make(true);
        }

        // dd(mt_rand());
        return view('BackEnd.Account.account');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'name'=>'required',
            'user_name'=>'required|regex:/(^([a-zA-z]+)(\d+)?$)/u|unique:users,username',
            'level'=>'required',
            'password'=>'required',
            'email'=>'required|email|unique:users,email',
        ]);
        if ($validator->fails()) {
            return response()->json([
                'status'=>400,
                'errors'=>$validator->messages(),
            ]);
        }
        else{
            $account = new User();
            if ($account) {
                $account->name = $request->name;
                $account->username = $request->user_name;
                $account->email = $request->email;
                $account->level = $request->level;
                $account->password = Hash::make($request->password);
                $account->save();

                return response()->json([
                    'status'=>200,
                    'message'=>'Add Account Successfully',
                ]);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        if (request()->ajax()) {
            $account = User::find($id);

            $output = '';
            if ($account) {
                $output .= '
                  <p><label><img alt="image" class="img-thumbnail" src="'.url('backend/icon.png').'" height="48px" width="48px" /></label></p>
                  <p><label>Name: '.$account->name.'</label></p>
                  <p><label>User Name: '.$account->username.'</label></p>
                  <p><label>Phone : </label> '.$account->phone.'</p>
                ';

                // echo $output;
                return response()->json([
                    'data' => $output
                ]);
            }else{
                return response()->json([
                    'status' => 404,
                    'message' => 'Account Not Found'
                ]);
            }
        }
    }

        /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id){
        $account = User::findOrFail($id);
        if ($account) {
            return response()->json([
                'status'=>200,
                'profile_login'=>$account,
            ]);
        }else{
            return response()->json([
                'status'=>404,
                'message'=>'Account Not Found',
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(),[
            'name'=>'required',
            'user_name'=>'required|unique:users,username',
            'level'=>'required',
            'email'=>'required|email|unique:users,email',
        ]);
        if ($validator->fails()) {
            return response()->json([
                'status'=>400,
                'errors'=>$validator->messages(),
            ]);
        }
        else{
            $account = User::findOrFail($id);
            if ($account) {
                $account->name = $request->name;
                $account->username = $request->user_name;
                $account->email = $request->email;
                $account->level = $request->level;
                if ($request->password){
                    $account->password = Hash::make($request->password);
                }
                $account->save();

                return response()->json([
                    'status'=>200,
                    'message'=>'Update Account Successfully',
                ]);
            }
            else{
                return response()->json([
                    'status'=>404,
                    'message'=>'Account Not Found',
                ]);
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $users = User::findOrFail($id);
        if ($users) {
            $users->delete();
            return response()->json([
                'status'=>200,
                'message'=>'Delete Successfully',
            ]);

        }else{
            return response()->json([
                'status'=>404,
                'message'=>'Account Not Found',
            ]);
        }

    }
}

app/Http/Controllers/BackEnd/CategoryController.php
<?php

namespace App\Http\Controllers\BackEnd;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (request()->ajax()) {
            return datatables()->of(Category::whereNull('category_sub')->orderBy('category_sorting','ASC')->get())
                ->addColumn('action', function($data){
                        $button = '<button type="button" name="edit" id="edit" data-category_id="'.$data->category_id.'" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i></button>';
                        $button .= '&nbsp;&nbsp;';
                        $button .= '<button type="button" name="delete" id="'.$data->category_id.'" data-category_id="'.$data->category_id.'" class="btn  btn-outline btn-danger delete"><i class="fa fa-trash"></i></button>';
                        return $button;
                })
                ->rawColumns(['action'])->make(true);
        }
        $categories = Category::where('category_status',1)
        ->whereNull('category_sub')
        ->with('childrenCategories')
        ->get();

        return view('BackEnd.Category.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (request()->ajax()) {
            return datatables()->of(Category::whereNotNull('category_sub')->orderBy('category_sorting','ASC')->get())
                ->addColumn('action', function($data){
                        $button = '<button type="button" name="edit" id="edit" data-category_id="'.$data->category_id.'" class="btn btn-outline btn-primary"><i class="fa fa-edit"></i></button>';
                        $button .= '&nbsp;&nbsp;';
                        $button .= '<button type="button" name="delete" id="'.$data->category_id.'" data-category_id="'.$data->category_id.'" class="btn  btn-outline btn-danger delete"><i class="fa fa-trash"></i></button>';
                        return $button;
                })
                ->addColumn('category_parent', function($data){
                    $span = ' '.$data->cateParent->category_name.' ';
                    return $span;
                })
                ->rawColumns(['action','category_parent'])->make(true);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->ajax()) {
            $validator = Validator::make($request->all(),[
                'category_name'=>'required',
                'slug_category_product'=>'required',
                'category_status'=>'required',
                'category_icon'=>'required',
            ]);
            if ($validator->fails()) {
                return response()->json([
                    'status'=>400,
                    'errors'=>$validator->messages(),
                ]);
            }
            else{
                $category = new Category();
                if ($category) {
                    $category->category_name = $request->category_name;
                    $category->category_slug  = $request->slug_category_product;
                    $category->category_sub = $request->category_sub;
                    $category->category_status = $request->category_status;
                    $category->category_icon = $request->category_icon;
                    $category->category_sorting = count(Category::all())+1;
                    $category->save();

                    return response()->json([
                        'status'=>200,
                        'message'=>'Update Category Successfully',
                    ]);
                }
                else{
                    return response()->json([
                        'status'=>404,
                        'message'=>'Category Not Found',
                    ]);
                }
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (request()->ajax()) {
            $category = Category::findOrFail($id);
            if ($category) {
                return response()->json([
                    'status'=>200,
                    'category'=>$category,
                ]);
            }else{
                return response()->json([
                    'status'=>404,
                    'message'=>'Category Not Found',
                ]);
            }
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->ajax()) {
            $validator = Validator::make($request->all(),[
                'category_name'=>'required',
                'slug_category_product'=>'required',
                'category_status'=>'required',
            ]);
            if ($validator->fails()) {
                return response()->json([
                    'status'=>400,
                    'errors'=>$validator->messages(),
                ]);
            }
            else{
                $category = Category::findOrFail($id);
                if ($category) {
                    $category->category_name = $request->category_name;
                    $category->category_slug  = $request->slug_category_product;
                    $category->category_sub = $request->category_sub;
                    $category->category_status = $request->category_status;
                    $category->category_icon = $request->category_icon;
                    $category->save();

                    return response()->json([
                        'status'=>200,
                        'message'=>'Update Category Successfully',
                    ]);
                }
                else{
                    return response()->json([
                        'status'=>404,
                        'message'=>'Category Not Found',
                    ]);
                }
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        if ($category) {
            $category->delete();

            return response()->json([
                'status'=>200,
                'message'=>'Delete Successfully',
            ]);
        }else{
            return response()->json([
                'status'=>404,
                'message'=>'Category Not Found',
            ]);
        }
    }
}

resources/views/BackEnd/Gallery/list.blade.php
@extends('Layout_admin')
@section('title')
    Gallery
@endsection
@section('content')

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Tables Product</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a>Product</a>
                </li>
                <li class="breadcrumb-item">
                    <a>List Product</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>List Gallery</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper-content" style="margin-bottom: -5%;">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-content">
                        <form action="{{ route('product-gallery.update', [$pro_id]) }}" class="dropzone"
                            id="dropzoneForm" style="border: 1px dashed #1ab394;">
                            @method('PUT')
                            @csrf
                            <div class="fallback">
                                <input name="file" type="file" multiple />
                            </div>
                        </form>
                        <div align="center" style="margin-top: 1%;">
                            <button type="button" class="btn btn-info" id="submit-all">Upload</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Gallery</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-product">
                                <li><a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li><a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <input type="hidden" name="pro_id" class="pro_id" value="{{ $pro_id }}">
                        <form>
                            @csrf
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                        <tr style="text-transform: capitalize;">
                                            <th>ID</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody id="gallery_load">

                                    </tbody>
                                    <tfoot>
                                        <tr style="text-transform: capitalize;">
                                            <th>ID</th>
                                            <th>Image</th>
                                            <th>Action</th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('css')
    <link href="{{ asset('backend/css/plugins/dropzone/basic.css') }}" rel="stylesheet">
    <link href="{{ asset('backend/css/plugins/dropzone/dropzone.css') }}" rel="stylesheet">
@endsection
@section('script')
    <script src="{{ asset('backend/js/plugins/dropzone/dropzone.js') }}"></script>
    <script>
        $(document).ready(function() {
            load_gallery();

            // Delete
            $(document).on('click', '.delete-gallery', function() {
                var del_id = $(this).data('gal_id');
                var _token = $('input[name="_token"]').val();
                if (confirm('Bạn chắc chắn muốn xóa?')) {
                    $.ajax({
                        url: '{{ route('product-gallery.store') }}',
                        method: 'POST',
                        data: {
                            del_id: del_id,
                            _token: _token
                        },
                        success: function(data) {
                            load_gallery();
                            toastr.success('Delete Successfully', 'Notification');
                        }

                    });
                }
            });
            // Update Image
            $(document).on('change', '.file_image', function() {
                var up_id = $(this).data('gal_id');
                var image = document.getElementById('file-' + up_id).files[0];
                var form_data = new FormData();
                form_data.append("file", document.getElementById('file-' + up_id).files[0]);
                form_data.append("up_id", up_id);

                $.ajax({
                    url: '{{ route('product-gallery.store') }}',
                    method: 'POST',
                    data: form_data,
                    contentType: false,
                    cache: false,
                    processData: false,
                    success: function(data) {
                        load_gallery();
                        toastr.success('Update Successfully', 'Notification');
                    }

                });
            });

        });

        function load_gallery() {
            var pro_id = $('.pro_id').val();

            $.ajax({
                url: '{{ route('product-gallery.create') }}',
                method: 'get',
                data: {
                    pro_id: pro_id,
                },
                dataType: 'json',
                success: function(response) {
                    $('#gallery_load').html(response.data);
                }

            });
        }
        Dropzone.options.dropzoneForm = {
            paramName: "file", // The name that will be used to transfer the file
            maxFilesize: 2, // MB
            dictDefaultMessage: "<strong>Drop files here or click to upload. </strong></br> (This is just a demo dropzone. Selected files are not actually uploaded.)",
            autoProcessQueue: false,
            acceptedFiles: ".png,.jpg,.gif,.bmp,.jpeg",
            init: function() {
                var submitButton = document.querySelector("#submit-all");
                myDropzone = this;

                submitButton.addEventListener('click', function() {
                    myDropzone.processQueue();
                });

                this.on("complete", function() {
                    if (this.getQueuedFiles().length == 0 && this.getUploadingFiles().length == 0) {
                        var _this = this;
                        _this.removeAllFiles();
                    }
                    load_gallery();
                });

            }

        };
    </script>
@endsection